language: ruby
os: linux
dist: focal
env:
  global:
    - DOCKER_REPO=dockerpirate/unbound
    - ALPINE_M=3
    - ALPINE_P=12
    - UNBOUND_M=1.13.1
    - UNBOUND_P=r3
    - LDNS=1.7.1-r1
before_install:
  - curl -fsSL https://get.docker.com | sh
  - echo '{"experimental":"enabled"}' | sudo tee /etc/docker/daemon.json
  - mkdir -p $HOME/.docker
  - echo '{"experimental":"enabled"}' | sudo tee $HOME/.docker/config.json
  - sudo service docker start
install:
  - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
  - docker buildx create --name xbuilder --use
script: bash ci.sh
